/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activeapps;

import static activeapps.PesertaSessionPanel.TulisNilaiKeFile;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.Timer;

/**
 *
 * @author daniar heri
 */
public class Computerise extends ImagePanelBackGround {

    public static final int DefaultTime = 90*60 ; // detik
    public static int TimeRemaining;
    Timer countdownTimer ;
    private Vector<SoalPG> ListSoal = new Vector<SoalPG>();
    private int currNo = 0; // relative thd 1
    boolean IsHide = false;
    
    public Computerise(String Path) {
        super(Path);
        initComponents();
        ShowTimer.setEnabled(false);
    }
    
    private void SetPanelSoal(SoalPG SatuSoal){
        currNo = SatuSoal.No;
        No.setText(Integer.toString(SatuSoal.No)+".");
        Soal.setText(SatuSoal.Soal);
        PilA.setText(SatuSoal.PilA);
        PilB.setText(SatuSoal.PilB);
        PilC.setText(SatuSoal.PilC);
        PilD.setText(SatuSoal.PilD);            
        bgAnswer.clearSelection();
        if(currNo == ListSoal.size()){
            NextSoal.setEnabled(false);
            Selesai.setEnabled(true);
            currNo = -99;
        }
    }
    
    public void loadFromFile (String fileName) throws IOException{
    	BufferedReader reader = new BufferedReader(new FileReader(fileName));
    	String line = null;
        int i = 0;
    	while ((line = reader.readLine()) != null) {
                SoalPG SatuSoal = new SoalPG();
                SatuSoal.No = i+1;
                SatuSoal.Soal = line;
                SatuSoal.PilA = reader.readLine();
                SatuSoal.PilB = reader.readLine();
                SatuSoal.PilC = reader.readLine();
                SatuSoal.PilD = reader.readLine();
                SatuSoal.Kunci = reader.readLine().trim();
    		ListSoal.add(SatuSoal);
                i++;
    	}
        reader.close();
    }
    
    public String Jawaban(){
        for (Enumeration<AbstractButton> buttons = bgAnswer.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            if(button.isSelected())
                return button.getActionCommand();
        }
        return "X"; // belum menjawab
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAnswer = new javax.swing.ButtonGroup();
        PanelSoal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Soal = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        rA = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PilA = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        rB = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        PilB = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        rC = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        PilC = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        rD = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        PilD = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        ShowTimer = new javax.swing.JButton();
        HideTimer = new javax.swing.JButton();
        LabelTimer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        No = new javax.swing.JLabel();
        NextSoal = new javax.swing.JButton();
        Selesai = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSoal.setOpaque(false);
        PanelSoal.setPreferredSize(new java.awt.Dimension(500, 263));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setOpaque(false);

        Soal.setEditable(false);
        Soal.setColumns(40);
        Soal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Soal.setLineWrap(true);
        Soal.setRows(8);
        Soal.setTabSize(1);
        Soal.setWrapStyleWord(true);
        Soal.setBorder(null);
        Soal.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jScrollPane2.setViewportView(Soal);

        PanelSoal.add(jScrollPane2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        rA.setBackground(new java.awt.Color(255, 255, 255));
        rA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rA.setText("a.");
        rA.setActionCommand("a");
        rA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rA.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        rA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        PilA.setEditable(false);
        PilA.setColumns(45);
        PilA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PilA.setLineWrap(true);
        PilA.setRows(2);
        PilA.setTabSize(12);
        PilA.setWrapStyleWord(true);
        PilA.setBorder(null);
        PilA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(PilA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(rA)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rA)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        rA.getAccessibleContext().setAccessibleParent(PanelSoal);

        PanelSoal.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rB.setBackground(new java.awt.Color(255, 255, 255));
        rB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rB.setText("b.");
        rB.setActionCommand("b");

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);
        jScrollPane4.setOpaque(false);

        PilB.setEditable(false);
        PilB.setColumns(45);
        PilB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PilB.setLineWrap(true);
        PilB.setRows(2);
        PilB.setTabSize(5);
        PilB.setWrapStyleWord(true);
        PilB.setBorder(null);
        PilB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(PilB);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rB)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rB)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        PanelSoal.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rC.setBackground(new java.awt.Color(255, 255, 255));
        rC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rC.setText("c.");
        rC.setActionCommand("c");

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);
        jScrollPane5.setOpaque(false);

        PilC.setEditable(false);
        PilC.setColumns(45);
        PilC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PilC.setLineWrap(true);
        PilC.setRows(2);
        PilC.setTabSize(5);
        PilC.setWrapStyleWord(true);
        PilC.setBorder(null);
        PilC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane5.setViewportView(PilC);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rC)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rC)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        PanelSoal.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        rD.setBackground(new java.awt.Color(255, 255, 255));
        rD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rD.setText("d.");
        rD.setActionCommand("d");
        rD.setOpaque(false);

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);
        jScrollPane6.setOpaque(false);

        PilD.setEditable(false);
        PilD.setColumns(45);
        PilD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PilD.setLineWrap(true);
        PilD.setRows(2);
        PilD.setTabSize(5);
        PilD.setWrapStyleWord(true);
        PilD.setBorder(null);
        PilD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane6.setViewportView(PilD);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rD)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rD)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        PanelSoal.add(jPanel4);

        add(PanelSoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 630, 400));

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 600));

        jPanel10.setOpaque(false);

        ShowTimer.setBackground(new java.awt.Color(0, 0, 0));
        ShowTimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ShowTimer.setForeground(new java.awt.Color(255, 255, 255));
        ShowTimer.setText("Show Timer");
        ShowTimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTimerMouseClicked(evt);
            }
        });

        HideTimer.setBackground(new java.awt.Color(0, 0, 0));
        HideTimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        HideTimer.setForeground(new java.awt.Color(255, 255, 255));
        HideTimer.setText("Hide Timer");
        HideTimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideTimerMouseClicked(evt);
            }
        });

        LabelTimer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTimer.setText("00:00:00");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIMER");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(ShowTimer)
                        .addGap(17, 17, 17)
                        .addComponent(HideTimer)))
                .addGap(44, 44, 44))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowTimer)
                    .addComponent(HideTimer))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 280, 530));

        No.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        No.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        No.setText("1");
        No.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 70, 50));

        NextSoal.setBackground(new java.awt.Color(0, 0, 0));
        NextSoal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NextSoal.setForeground(new java.awt.Color(255, 255, 255));
        NextSoal.setText("Next");
        NextSoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextSoalMouseClicked(evt);
            }
        });
        add(NextSoal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 80, -1));

        Selesai.setBackground(new java.awt.Color(0, 0, 0));
        Selesai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Selesai.setForeground(new java.awt.Color(255, 255, 255));
        Selesai.setText("Finish");
        Selesai.setEnabled(false);
        Selesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelesaiMouseClicked(evt);
            }
        });
        add(Selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rAActionPerformed

    private void NextSoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextSoalMouseClicked
        if(NextSoal.isEnabled()){
            if(Jawaban().compareTo("X")!=0){
                if (Jawaban().compareTo(ListSoal.elementAt(currNo-1).Kunci)==0)
                    PesertaSessionPanel.Score += PesertaSessionPanel.NilaiBenar;
                else
                    PesertaSessionPanel.Score -= 1;
            }
                SetPanelSoal(ListSoal.elementAt(currNo));
        }    
    }//GEN-LAST:event_NextSoalMouseClicked

    private void SelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelesaiMouseClicked
        if(Selesai.isEnabled()){
            if (Jawaban().compareTo("X")!=0){
                if (Jawaban().compareTo(ListSoal.lastElement().Kunci)==0)
                    PesertaSessionPanel.Score += PesertaSessionPanel.NilaiBenar;
                else
                    PesertaSessionPanel.Score -= 1; 
                countdownTimer.stop();
            }
                JOptionPane.showMessageDialog(this, "Selamat! Anda telah menyelesaikan soal pilihan ganda.", "Answer complete", JOptionPane.INFORMATION_MESSAGE);
                MainFrame.SetNewPanel("SoalMenjodohkan");
        }
    }//GEN-LAST:event_SelesaiMouseClicked

    private void ShowScore(){
        JOptionPane.showMessageDialog(this,"Score tim Anda adalah "+
                PesertaSessionPanel.Score+".","Score",JOptionPane.PLAIN_MESSAGE);
        countdownTimer.stop();
        TimeRemaining = 0;
        ListSoal.clear();
        currNo = 0;
        bgAnswer.clearSelection();
        NextSoal.setEnabled(true);
        Selesai.setEnabled(false);
        try {
            PesertaSessionPanel.TulisNilaiKeFile("NilaiPeserta.in");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Computerise.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Computerise.class.getName()).log(Level.SEVERE, null, ex);
        }
        PesertaSessionPanel.SudahMengerjakan = true;
        MainFrame.SetNewPanel("PesertaSession");
    }
    
    public void repaintLabel(int Second){
        if(IsHide){
            LabelTimer.setText("");
        }else{
            TimeRemaining = Second;
            int hh = Second/3600;
            int mm = (Second%3600)/60;
            int ss = (Second%3600)%60;
            String StrHH, StrMM, StrSS;
            if (hh < 10)
                StrHH = new String("0"+hh);
            else
                StrHH = new String(Integer.toString(hh));
            if (mm < 10)
                StrMM = new String("0"+mm);
            else
                StrMM = new String(Integer.toString(mm));
            if (ss < 10)
                StrSS = new String("0"+ss);
            else
                StrSS = new String(Integer.toString(ss));
            String Jam = new String(StrHH+":"+StrMM+":"+StrSS);

            LabelTimer.setText(Jam);
        }
    }
     
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        bgAnswer.add(rA);
        bgAnswer.add(rB);
        bgAnswer.add(rC);
        bgAnswer.add(rD);
        try {
            loadFromFile("SoalPG.in");
        } catch (IOException ex) {
            Logger.getLogger(Computerise.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Maaf! File SoalPG.in tidak tersedia.", "Loading error", JOptionPane.ERROR_MESSAGE);
        }
        SetPanelSoal(ListSoal.firstElement());
        countdownTimer = new Timer(1000, new Computerise.CountdownTimerListener(DefaultTime));
        repaintLabel(DefaultTime);
        countdownTimer.start();
    }//GEN-LAST:event_formComponentShown

    private void HideTimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideTimerMouseClicked
        if (HideTimer.isEnabled()){
            IsHide = true;
            HideTimer.setEnabled(false);
            ShowTimer.setEnabled(true);
        }
    }//GEN-LAST:event_HideTimerMouseClicked

    private void ShowTimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTimerMouseClicked
        if(ShowTimer.isEnabled()){
            IsHide = false;
            HideTimer.setEnabled(true);
            ShowTimer.setEnabled(false);
        }
    }//GEN-LAST:event_ShowTimerMouseClicked
    
    class CountdownTimerListener implements ActionListener{
        int timeRemaining ;
        
        public CountdownTimerListener(int Time){
            timeRemaining = Time;
        }
    
        @Override
        public void actionPerformed(ActionEvent e) {
            if (--timeRemaining > 0){
                repaintLabel(timeRemaining);
            }else{
                LabelTimer.setText("Time's up!");
                ShowScore();
                countdownTimer.stop();
            }
        }
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HideTimer;
    private javax.swing.JLabel LabelTimer;
    private javax.swing.JButton NextSoal;
    private javax.swing.JLabel No;
    private javax.swing.JPanel PanelSoal;
    private javax.swing.JTextArea PilA;
    private javax.swing.JTextArea PilB;
    private javax.swing.JTextArea PilC;
    private javax.swing.JTextArea PilD;
    private javax.swing.JButton Selesai;
    private javax.swing.JButton ShowTimer;
    private javax.swing.JTextArea Soal;
    private javax.swing.ButtonGroup bgAnswer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JRadioButton rA;
    private javax.swing.JRadioButton rB;
    private javax.swing.JRadioButton rC;
    private javax.swing.JRadioButton rD;
    // End of variables declaration//GEN-END:variables
}
