/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activeapps;

import java.io.File;

/**
 *
 * @author daniar heri
 */
public class PanitiaSessionPanel extends ImagePanelBackGround {

    /**
     * Creates new form AdminSessionPanel
     */
    public PanitiaSessionPanel(String Path) {
        super(Path);
        initComponents();
        setSize(MainFrame.FRAME_WIDTH, MainFrame.FRAME_HEIGHT);
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AMQButton = new javax.swing.JButton();
        GrandFinalButton = new javax.swing.JButton();
        Sesi3 = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        DebateButton = new javax.swing.JButton();
        AccButton = new javax.swing.JButton();
        Timer = new javax.swing.JButton();

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(324, 458));

        AMQButton.setBackground(new java.awt.Color(0, 0, 0));
        AMQButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AMQButton.setForeground(new java.awt.Color(255, 255, 255));
        AMQButton.setText("Access Manual Qualification");
        AMQButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AMQButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMQButtonMouseClicked(evt);
            }
        });

        GrandFinalButton.setBackground(new java.awt.Color(0, 0, 0));
        GrandFinalButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GrandFinalButton.setForeground(new java.awt.Color(255, 255, 255));
        GrandFinalButton.setText("Access Grand Final");
        GrandFinalButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        GrandFinalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrandFinalButtonMouseClicked(evt);
            }
        });

        Sesi3.setBackground(new java.awt.Color(0, 0, 0));
        Sesi3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sesi3.setForeground(new java.awt.Color(255, 255, 255));
        Sesi3.setText("Access Computerized Qualification");
        Sesi3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Sesi3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sesi3MouseClicked(evt);
            }
        });
        Sesi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sesi3ActionPerformed(evt);
            }
        });

        Kembali.setBackground(new java.awt.Color(0, 0, 0));
        Kembali.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Kembali.setForeground(new java.awt.Color(255, 255, 255));
        Kembali.setText("Logout");
        Kembali.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });

        DebateButton.setBackground(new java.awt.Color(0, 0, 0));
        DebateButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DebateButton.setForeground(new java.awt.Color(255, 255, 255));
        DebateButton.setText("Debate Competition");
        DebateButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        DebateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DebateButtonMouseClicked(evt);
            }
        });

        AccButton.setBackground(new java.awt.Color(0, 0, 0));
        AccButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AccButton.setForeground(new java.awt.Color(255, 255, 255));
        AccButton.setText("Accurate");
        AccButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AccButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccButtonMouseClicked(evt);
            }
        });
        AccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccButtonActionPerformed(evt);
            }
        });

        Timer.setBackground(new java.awt.Color(0, 0, 0));
        Timer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Timer.setForeground(new java.awt.Color(255, 255, 255));
        Timer.setText("Timer");
        Timer.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Timer.setPreferredSize(new java.awt.Dimension(64, 23));
        Timer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AMQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GrandFinalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DebateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sesi3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(AMQButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sesi3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DebateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GrandFinalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(Kembali)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(766, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        // TODO add your handling code here:
        MainFrame.SetNewPanel("Login");
    }//GEN-LAST:event_KembaliMouseClicked
        
    private void AMQButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMQButtonMouseClicked
        MainFrame.SetNewPanel("AMQ");
    }//GEN-LAST:event_AMQButtonMouseClicked

    private void GrandFinalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrandFinalButtonMouseClicked
        if(!IsFileExist())
            MainFrame.SetNewPanel("InputTeam");
        else
            MainFrame.SetNewPanel("GrandFinal");
    }//GEN-LAST:event_GrandFinalButtonMouseClicked

    private void DebateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DebateButtonMouseClicked
        MainFrame.SetNewPanel("Debate");
    }//GEN-LAST:event_DebateButtonMouseClicked

    private void Sesi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sesi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sesi3ActionPerformed

    private void AccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccButtonActionPerformed

    private void TimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimerMouseClicked
        MainFrame.SetNewPanel("Sesi1");
    }//GEN-LAST:event_TimerMouseClicked

    private void Sesi3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sesi3MouseClicked
        MainFrame.SetNewPanel("ACQ");
    }//GEN-LAST:event_Sesi3MouseClicked

    private void AccButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccButtonMouseClicked
        MainFrame.SetNewPanel("ACC");
    }//GEN-LAST:event_AccButtonMouseClicked

    private boolean IsFileExist(){
        File file = new File("DataTeam.txt");
        return file.exists();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AMQButton;
    private javax.swing.JButton AccButton;
    private javax.swing.JButton DebateButton;
    private javax.swing.JButton GrandFinalButton;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Sesi3;
    private javax.swing.JButton Timer;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
