/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activeapps;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author daniar heri
 */
public class PesertaSessionPanel extends ImagePanelBackGround {
    
    public static String  NamaTim = new String("Undefined");
    public static int Score = 0;
    
    public static final int NilaiBenar = 4;
    public static final int NilaiSalah = -1;
    public static boolean SudahMengerjakan = false;
    
    public PesertaSessionPanel(String Path) {
        super(Path);
        initComponents();
        setSize(MainFrame.FRAME_WIDTH, MainFrame.FRAME_HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Nilai = new javax.swing.JButton();
        EditProfile = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        Mulai = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Petunjuk");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        Nilai.setBackground(new java.awt.Color(0, 0, 0));
        Nilai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nilai.setForeground(new java.awt.Color(255, 255, 255));
        Nilai.setText("Nilai");
        Nilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Nilai.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Nilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NilaiMouseClicked(evt);
            }
        });

        EditProfile.setBackground(new java.awt.Color(0, 0, 0));
        EditProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EditProfile.setForeground(new java.awt.Color(255, 255, 255));
        EditProfile.setText("Profile");
        EditProfile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditProfile.setMargin(new java.awt.Insets(2, 4, 2, 4));
        EditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditProfileMouseClicked(evt);
            }
        });

        Kembali.setBackground(new java.awt.Color(0, 0, 0));
        Kembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Kembali.setForeground(new java.awt.Color(255, 255, 255));
        Kembali.setText("Logout");
        Kembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });

        Mulai.setBackground(new java.awt.Color(0, 0, 0));
        Mulai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mulai.setForeground(new java.awt.Color(255, 255, 255));
        Mulai.setText("Mulai");
        Mulai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Mulai.setMargin(new java.awt.Insets(2, 4, 2, 4));
        Mulai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MulaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EditProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(937, 937, 937)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        MainFrame.SetNewPanel("Login");
        try {
            TulisNilaiKeFile("NilaiPeserta.in");
        } catch (IOException ex) {
            Logger.getLogger(TTS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_KembaliMouseClicked

    private void MulaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MulaiMouseClicked
        if (!SudahMengerjakan)
            MainFrame.SetNewPanel("Computerise");
        else
            JOptionPane.showMessageDialog(this, "Maaf! Anda sudah mengerjakan soal ini.", "Message", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_MulaiMouseClicked

    private void EditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditProfileMouseClicked

        JOptionPane.showMessageDialog ( 
        this, "Nama tim Anda adalah "+NamaTim+".","Nama Tim", 
        JOptionPane.INFORMATION_MESSAGE); 
    }//GEN-LAST:event_EditProfileMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       if(NamaTim.compareTo("Undefined")== 0 )
           NamaTim = 
                JOptionPane.showInputDialog ( this,"Masukkan nama tim Anda" );
       //System.out.println(" ini "+this);
    }//GEN-LAST:event_formComponentShown

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JOptionPane.showMessageDialog(this, "Klik \"Mulai\" untuk memulai mengerjakan soal.\n"
        + "Klik \"Profile\" untuk melihat nama tim Anda.\n"
                + "Klik \"Nilai\" untuk melihat score tim Anda.", "Petunjuk", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void NilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NilaiMouseClicked
        if(SudahMengerjakan)
            JOptionPane.showMessageDialog(this, "Score tim Anda adalah "+Score, "Score tim "+NamaTim, JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Maaf! Anda belum mengerjakan soal.", "Score tim "+NamaTim, JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_NilaiMouseClicked
 
    
    public static void TulisNilaiKeFile(String FileName) throws FileNotFoundException, UnsupportedEncodingException{
        PrintWriter writer = new PrintWriter(FileName, "UTF-8");
            writer.println(NamaTim+"\n"+Score);
        writer.close();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditProfile;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Mulai;
    private javax.swing.JButton Nilai;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
