/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activeapps;

import static activeapps.TTS.Kolom;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Collections;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author daniar heri
 */
public class TictacPanel extends ImagePanelBackGround {

    /**
     * Creates new form TictacPanel
     */
    private int DefaultTime = 45*60 ; // detik
    private static int Default45 = 0 ; // detik
    Timer countdownTimer,countdown45;
    Vector<Integer> RandomNilai = new Vector<Integer>();
    
    public static ImagePanelTictac Kolom[][] = new ImagePanelTictac[5][5];
    
    public TictacPanel(String Path) {
        super(Path);
        initComponents();
        start.setEnabled(false);
        stop.setEnabled(false);
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTimer = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Score3 = new javax.swing.JLabel();
        AddButton3 = new javax.swing.JButton();
        TambahanScore3 = new javax.swing.JTextField();
        NamaTim3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Score5 = new javax.swing.JLabel();
        AddButton5 = new javax.swing.JButton();
        TambahanScore5 = new javax.swing.JTextField();
        NamaTim5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Score2 = new javax.swing.JLabel();
        TambahanScore2 = new javax.swing.JTextField();
        AddButton2 = new javax.swing.JButton();
        NamaTim2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Score4 = new javax.swing.JLabel();
        AddButton4 = new javax.swing.JButton();
        TambahanScore4 = new javax.swing.JTextField();
        NamaTim4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NamaTim1 = new javax.swing.JLabel();
        Score1 = new javax.swing.JLabel();
        AddButton1 = new javax.swing.JButton();
        TambahanScore1 = new javax.swing.JTextField();
        LabelTimer45 = new javax.swing.JLabel();
        PanelTictac = new javax.swing.JPanel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        LabelTimer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTimer.setText("00:00:00");

        start.setBackground(new java.awt.Color(0, 0, 0));
        start.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("Start Timer");
        start.setMargin(new java.awt.Insets(2, 4, 2, 4));
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });

        stop.setBackground(new java.awt.Color(0, 0, 0));
        stop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 255, 255));
        stop.setText("Stop Timer");
        stop.setMargin(new java.awt.Insets(2, 4, 2, 4));
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        Kembali.setBackground(new java.awt.Color(0, 0, 0));
        Kembali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Kembali.setForeground(new java.awt.Color(255, 255, 255));
        Kembali.setText("Kembali");
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SCORE TABLE");

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(1024, 85));

        jPanel9.setOpaque(false);

        Score3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score3.setText("0");

        AddButton3.setBackground(new java.awt.Color(0, 0, 0));
        AddButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton3.setForeground(new java.awt.Color(255, 255, 255));
        AddButton3.setText("add");
        AddButton3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton3MouseClicked(evt);
            }
        });

        TambahanScore3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore3.setText("0");
        TambahanScore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore3ActionPerformed(evt);
            }
        });

        NamaTim3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim3.setText(" ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(TambahanScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddButton3)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(NamaTim3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton3)
                    .addComponent(TambahanScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel10.setOpaque(false);

        Score5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score5.setText("0");

        AddButton5.setBackground(new java.awt.Color(0, 0, 0));
        AddButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton5.setForeground(new java.awt.Color(255, 255, 255));
        AddButton5.setText("add");
        AddButton5.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AddButton5MouseDragged(evt);
            }
        });
        AddButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton5MouseClicked(evt);
            }
        });

        TambahanScore5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore5.setText("0");
        TambahanScore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore5ActionPerformed(evt);
            }
        });

        NamaTim5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim5.setText(" ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(TambahanScore5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddButton5)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(NamaTim5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton5)
                    .addComponent(TambahanScore5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel11.setOpaque(false);

        Score2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score2.setText("0");

        TambahanScore2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore2.setText("0");
        TambahanScore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore2ActionPerformed(evt);
            }
        });

        AddButton2.setBackground(new java.awt.Color(0, 0, 0));
        AddButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton2.setForeground(new java.awt.Color(255, 255, 255));
        AddButton2.setText("add");
        AddButton2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton2MouseClicked(evt);
            }
        });

        NamaTim2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim2.setText(" ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TambahanScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(AddButton2)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(NamaTim2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton2)
                    .addComponent(TambahanScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel12.setOpaque(false);

        Score4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score4.setText("0");

        AddButton4.setBackground(new java.awt.Color(0, 0, 0));
        AddButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton4.setForeground(new java.awt.Color(255, 255, 255));
        AddButton4.setText("add");
        AddButton4.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton4MouseClicked(evt);
            }
        });

        TambahanScore4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore4.setText("0");
        TambahanScore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore4ActionPerformed(evt);
            }
        });

        NamaTim4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim4.setText(" ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(TambahanScore4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddButton4)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(NamaTim4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton4)
                    .addComponent(TambahanScore4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel8.setOpaque(false);

        NamaTim1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim1.setText(" ");

        Score1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score1.setText("0");

        AddButton1.setBackground(new java.awt.Color(0, 0, 0));
        AddButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton1.setForeground(new java.awt.Color(255, 255, 255));
        AddButton1.setText("add");
        AddButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton1MouseClicked(evt);
            }
        });

        TambahanScore1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore1.setText("0");
        TambahanScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(AddButton1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(Score1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaTim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TambahanScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(NamaTim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Score1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton1)
                    .addComponent(TambahanScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LabelTimer45.setBackground(new java.awt.Color(204, 0, 153));
        LabelTimer45.setFont(new java.awt.Font("Tahoma", 0, 95)); // NOI18N
        LabelTimer45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTimer45.setText("00:00:00");

        javax.swing.GroupLayout PanelTictacLayout = new javax.swing.GroupLayout(PanelTictac);
        PanelTictac.setLayout(PanelTictacLayout);
        PanelTictacLayout.setHorizontalGroup(
            PanelTictacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        PanelTictacLayout.setVerticalGroup(
            PanelTictacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(475, 475, 475)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(LabelTimer45, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(95, 95, 95)
                        .addComponent(PanelTictac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1050, 1050, 1050)
                        .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelTimer45, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(PanelTictac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        if (start.isEnabled()){
            start.setEnabled(false);
            stop.setEnabled(true);
            countdown45 = new Timer(1000, new TictacPanel.CountdownTimerListener45(Default45));
            countdown45.start();
        }
    }//GEN-LAST:event_startMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        if (stop.isEnabled()){
            stop.setEnabled(false);
            start.setEnabled(false);
            repaintLabel45(0);
            countdown45.stop();
        }
    }//GEN-LAST:event_stopMouseClicked

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopActionPerformed

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
        try {
            GrandFinal.UpdateDataFile("DataTeam.txt");
        } catch (IOException ex) {
            Logger.getLogger(TTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        if ( countdownTimer.isRunning())
        countdownTimer.stop();
        MainFrame.SetNewPanel("GrandFinal");
    }//GEN-LAST:event_KembaliMouseClicked

    private void AddButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton3MouseClicked
        String str = TambahanScore3.getText();
        GrandFinal.Tim.elementAt(2).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore3.setText("0");
    }//GEN-LAST:event_AddButton3MouseClicked

    private void TambahanScore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore3ActionPerformed

    private void AddButton5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButton5MouseDragged

    private void AddButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton5MouseClicked
        String str = TambahanScore5.getText();
        GrandFinal.Tim.elementAt(4).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore5.setText("0");
    }//GEN-LAST:event_AddButton5MouseClicked

    private void TambahanScore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore5ActionPerformed

    private void TambahanScore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore2ActionPerformed

    private void AddButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton2MouseClicked
        String str = TambahanScore2.getText();
        GrandFinal.Tim.elementAt(1).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore2.setText("0");
    }//GEN-LAST:event_AddButton2MouseClicked

    private void AddButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton4MouseClicked
        String str = TambahanScore4.getText();
        GrandFinal.Tim.elementAt(3).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore4.setText("0");
    }//GEN-LAST:event_AddButton4MouseClicked

    private void TambahanScore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore4ActionPerformed

    private void AddButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton1MouseClicked
        String str = TambahanScore1.getText();
        GrandFinal.Tim.elementAt(0).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore1.setText("0");
    }//GEN-LAST:event_AddButton1MouseClicked

    private void TambahanScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        NamaTim1.setText(GrandFinal.Tim.elementAt(0).Nama);
        NamaTim2.setText(GrandFinal.Tim.elementAt(1).Nama);
        NamaTim3.setText(GrandFinal.Tim.elementAt(2).Nama);
        NamaTim4.setText(GrandFinal.Tim.elementAt(3).Nama);
        NamaTim5.setText(GrandFinal.Tim.elementAt(4).Nama);
        
        countdownTimer = new Timer(1000, new TictacPanel.CountdownTimerListener(DefaultTime));
        countdownTimer.start();
        UpdateScoreTable();
    }//GEN-LAST:event_formComponentShown

    public void bangkitkanRandom(){
        for (int i = 0; i < 10 ; i ++){
            RandomNilai.add(100);
        }
        for (int i = 0; i < 10 ; i ++){
            RandomNilai.add(50);
        }
        for (int i = 0; i < 5 ; i ++){
            RandomNilai.add(200);
        }
        Collections.shuffle(RandomNilai);
        Collections.shuffle(RandomNilai);
    }
    
    public void addComponents(){
        
        bangkitkanRandom();
        int z = 0;
        for (int i = 0 ; i < 5 ; i ++){
            for (int j = 0 ; j < 5 ; j ++){
                switch (RandomNilai.elementAt(z)){
                    case 50 : Kolom[i][j] = new ImagePanelTictac(50,30,i,j,"img/test/TictacClosed.png"); break;
                    case 100 : Kolom[i][j] = new ImagePanelTictac(100,60,i,j,"img/test/TictacClosed.png"); break;
                    case 200 : Kolom[i][j] = new ImagePanelTictac(200,90,i,j,"img/test/TictacClosed.png"); break;
                    default : System.out.println("Error d bagian random tictac nilai!");
                }
                z++;
            }
        }
        
        boolean shouldFill = true;
        PanelTictac.setLayout(new GridBagLayout());
        PanelTictac.setVisible(true);
        GridBagConstraints c = new GridBagConstraints();
	if (shouldFill) {
	//natural height, maximum width
	c.fill = GridBagConstraints.CENTER;
	}
        ///*
        for (int i = 0 ; i < 5 ;  i++){
            for (int j = 0 ; j < 5 ; j ++){               
                Kolom[i][j].setPreferredSize(new Dimension(Kolom[i][j].image.getWidth(),Kolom[i][j].image.getHeight()));
                
                c.gridy = i;
                c.gridx = j;
                PanelTictac.add(Kolom[i][j],c);
            }
        }
    }
    
    public static void BukaKolom(int X, int Y){
        try {        
            int Score = Kolom[X][Y].Score;
            start.setEnabled(true);
            Default45 = Kolom[X][Y].Time;
            
            repaintLabel45(Default45);
            Kolom[X][Y].Terbuka = true;
            Kolom[X][Y].image = ImageIO.read(new File("img/test/Tictac"+Score+".png"));
            Kolom[X][Y].setPreferredSize(new Dimension(Kolom[X][Y].image.getWidth(),Kolom[X][Y].image.getHeight()));
            Kolom[X][Y].repaint();
        } catch (IOException ex) {
            Logger.getLogger(TictacPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    class CountdownTimerListener implements ActionListener{
        int timeRemaining ;
        
        public CountdownTimerListener(int Time){
            timeRemaining = Time;
        }
    
        @Override
        public void actionPerformed(ActionEvent e) {
            if (--timeRemaining > 0){
                repaintLabel(timeRemaining);
            }else{
                LabelTimer.setText("Time's up!");
                countdownTimer.stop();
            }
        }
    }
    
    public void UpdateScoreTable(){
        Score1.setText(String.valueOf(GrandFinal.Tim.elementAt(0).Score));
        Score2.setText(String.valueOf(GrandFinal.Tim.elementAt(1).Score));
        Score3.setText(String.valueOf(GrandFinal.Tim.elementAt(2).Score));
        Score4.setText(String.valueOf(GrandFinal.Tim.elementAt(3).Score));
        Score5.setText(String.valueOf(GrandFinal.Tim.elementAt(4).Score));
    }
    
    public void repaintLabel(int Second){
        int hh = Second/3600;
        int mm = (Second%3600)/60;
        int ss = (Second%3600)%60;
        String StrHH, StrMM, StrSS;
        if (hh < 10)
            StrHH = new String("0"+hh);
        else
            StrHH = new String(Integer.toString(hh));
        if (mm < 10)
            StrMM = new String("0"+mm);
        else
            StrMM = new String(Integer.toString(mm));
        if (ss < 10)
            StrSS = new String("0"+ss);
        else
            StrSS = new String(Integer.toString(ss));
        String Jam = new String(StrHH+":"+StrMM+":"+StrSS);
        
        LabelTimer.setText(Jam);
    }
    
     public static void repaintLabel45(int Second){
        int hh = Second/3600;
        int mm = (Second%3600)/60;
        int ss = (Second%3600)%60;
        String StrHH, StrMM, StrSS;
        if (hh < 10)
            StrHH = new String("0"+hh);
        else
            StrHH = new String(Integer.toString(hh));
        if (mm < 10)
            StrMM = new String("0"+mm);
        else
            StrMM = new String(Integer.toString(mm));
        if (ss < 10)
            StrSS = new String("0"+ss);
        else
            StrSS = new String(Integer.toString(ss));
        String Jam = new String(StrHH+":"+StrMM+":"+StrSS);
        
        LabelTimer45.setText(Jam);
    }
     
     public static boolean IsTimerMati(){
         return (!start.isEnabled() && !stop.isEnabled());
         
     }
     
     class CountdownTimerListener45 implements ActionListener{
        int timeRemaining ;
        
        public CountdownTimerListener45(int Time){
            //System.out.println(Time+"  Masuuk "+timeRemaining);
            timeRemaining = Time;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            if (--timeRemaining > 0){
                
                repaintLabel45(timeRemaining);
            }else{
                LabelTimer45.setText("Time's up!");
                start.setEnabled(false);
                stop.setEnabled(false);
                countdown45.stop();
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton1;
    private javax.swing.JButton AddButton2;
    private javax.swing.JButton AddButton3;
    private javax.swing.JButton AddButton4;
    private javax.swing.JButton AddButton5;
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel LabelTimer;
    private static javax.swing.JLabel LabelTimer45;
    private javax.swing.JLabel NamaTim1;
    private javax.swing.JLabel NamaTim2;
    private javax.swing.JLabel NamaTim3;
    private javax.swing.JLabel NamaTim4;
    private javax.swing.JLabel NamaTim5;
    private javax.swing.JPanel PanelTictac;
    private javax.swing.JLabel Score1;
    private javax.swing.JLabel Score2;
    private javax.swing.JLabel Score3;
    private javax.swing.JLabel Score4;
    private javax.swing.JLabel Score5;
    private javax.swing.JTextField TambahanScore1;
    private javax.swing.JTextField TambahanScore2;
    private javax.swing.JTextField TambahanScore3;
    private javax.swing.JTextField TambahanScore4;
    private javax.swing.JTextField TambahanScore5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JButton start;
    public static javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
