/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activeapps;

import static activeapps.TTS.TinggiKolom;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author daniar heri
 */
public class TTS extends ImagePanelBackGround {

    /**
     * Creates new form TTS
     */
    private int DefaultTime = 45*60 ; // detik
    public static final int LebarKolom = 40;
    public static final int TinggiKolom = 31;
    final static boolean RIGHT_TO_LEFT = false;
    public static ImagePanel Kolom[][] = new ImagePanel[TinggiKolom][LebarKolom];
    public Vector<SoalTTS> ListSoal= new Vector<SoalTTS>();
    
    Timer countdownTimer;
    
    public TTS(String Path) {
        super(Path);
        initComponents();
        for (int i = 0 ; i < TinggiKolom; i ++){
            for (int j = 0 ; j < LebarKolom ; j ++){
                Kolom[i][j] = new ImagePanel('@');
                Kolom[i][j].AddNoSoal(0);
                //System.out.println("nih ");
            }
        }
        try {
            LoadTTSFromFile("SoalTTS.in");
        } catch (IOException ex) {
            Logger.getLogger(TTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        AddComponent();
        
        BeriPembatasHitam();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelTTS = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Kembali = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        V1 = new javax.swing.JButton();
        V2 = new javax.swing.JButton();
        V3 = new javax.swing.JButton();
        V4 = new javax.swing.JButton();
        V5 = new javax.swing.JButton();
        V6 = new javax.swing.JButton();
        V7 = new javax.swing.JButton();
        V8 = new javax.swing.JButton();
        V9 = new javax.swing.JButton();
        V10 = new javax.swing.JButton();
        MarkV = new javax.swing.JButton();
        SpinnerV = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        V11 = new javax.swing.JButton();
        V12 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        H1 = new javax.swing.JButton();
        H2 = new javax.swing.JButton();
        H3 = new javax.swing.JButton();
        H4 = new javax.swing.JButton();
        H5 = new javax.swing.JButton();
        H6 = new javax.swing.JButton();
        H7 = new javax.swing.JButton();
        H8 = new javax.swing.JButton();
        H9 = new javax.swing.JButton();
        H10 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        SpinnerH = new javax.swing.JSpinner();
        MarkH = new javax.swing.JButton();
        H11 = new javax.swing.JButton();
        H12 = new javax.swing.JButton();
        H13 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        LabelTimer = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Score3 = new javax.swing.JLabel();
        AddButton3 = new javax.swing.JButton();
        TambahanScore3 = new javax.swing.JTextField();
        NamaTim3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Score5 = new javax.swing.JLabel();
        AddButton5 = new javax.swing.JButton();
        TambahanScore5 = new javax.swing.JTextField();
        NamaTim5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Score2 = new javax.swing.JLabel();
        TambahanScore2 = new javax.swing.JTextField();
        AddButton2 = new javax.swing.JButton();
        NamaTim2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Score4 = new javax.swing.JLabel();
        AddButton4 = new javax.swing.JButton();
        TambahanScore4 = new javax.swing.JTextField();
        NamaTim4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NamaTim1 = new javax.swing.JLabel();
        Score1 = new javax.swing.JLabel();
        AddButton1 = new javax.swing.JButton();
        TambahanScore1 = new javax.swing.JTextField();

        setDoubleBuffered(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setOpaque(false);

        PanelTTS.setBackground(new java.awt.Color(0, 255, 255));
        PanelTTS.setMinimumSize(new java.awt.Dimension(300, 23));
        PanelTTS.setOpaque(false);
        PanelTTS.setLayout(new java.awt.GridBagLayout());

        jPanel5.setOpaque(false);

        Kembali.setBackground(new java.awt.Color(0, 0, 0));
        Kembali.setForeground(new java.awt.Color(255, 255, 255));
        Kembali.setText("Kembali");
        Kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KembaliMouseClicked(evt);
            }
        });

        jPanel4.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("MENURUN");

        V1.setBackground(new java.awt.Color(0, 0, 0));
        V1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V1.setForeground(new java.awt.Color(255, 255, 255));
        V1.setText("Nomor 1");
        V1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V1.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V1MouseClicked(evt);
            }
        });

        V2.setBackground(new java.awt.Color(0, 0, 0));
        V2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V2.setForeground(new java.awt.Color(255, 255, 255));
        V2.setText("Nomor 2");
        V2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V2.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V2MouseClicked(evt);
            }
        });

        V3.setBackground(new java.awt.Color(0, 0, 0));
        V3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V3.setForeground(new java.awt.Color(255, 255, 255));
        V3.setText("Nomor 3");
        V3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V3.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V3MouseClicked(evt);
            }
        });

        V4.setBackground(new java.awt.Color(0, 0, 0));
        V4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V4.setForeground(new java.awt.Color(255, 255, 255));
        V4.setText("Nomor 4");
        V4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V4.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V4MouseClicked(evt);
            }
        });

        V5.setBackground(new java.awt.Color(0, 0, 0));
        V5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V5.setForeground(new java.awt.Color(255, 255, 255));
        V5.setText("Nomor 5");
        V5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V5.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V5MouseClicked(evt);
            }
        });

        V6.setBackground(new java.awt.Color(0, 0, 0));
        V6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V6.setForeground(new java.awt.Color(255, 255, 255));
        V6.setText("Nomor 6");
        V6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V6.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                V6MouseDragged(evt);
            }
        });
        V6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V6MouseClicked(evt);
            }
        });

        V7.setBackground(new java.awt.Color(0, 0, 0));
        V7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V7.setForeground(new java.awt.Color(255, 255, 255));
        V7.setText("Nomor 7");
        V7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V7.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V7MouseClicked(evt);
            }
        });

        V8.setBackground(new java.awt.Color(0, 0, 0));
        V8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V8.setForeground(new java.awt.Color(255, 255, 255));
        V8.setText("Nomor 8");
        V8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V8.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V8MouseClicked(evt);
            }
        });

        V9.setBackground(new java.awt.Color(0, 0, 0));
        V9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V9.setForeground(new java.awt.Color(255, 255, 255));
        V9.setText("Nomor 9");
        V9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V9.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V9MouseClicked(evt);
            }
        });

        V10.setBackground(new java.awt.Color(0, 0, 0));
        V10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V10.setForeground(new java.awt.Color(255, 255, 255));
        V10.setText("Nomor 10");
        V10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V10.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V10MouseClicked(evt);
            }
        });

        MarkV.setBackground(new java.awt.Color(0, 0, 0));
        MarkV.setForeground(new java.awt.Color(255, 255, 255));
        MarkV.setText("Mark");
        MarkV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarkVMouseClicked(evt);
            }
        });

        SpinnerV.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Nomor");

        V11.setBackground(new java.awt.Color(0, 0, 0));
        V11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V11.setForeground(new java.awt.Color(255, 255, 255));
        V11.setText("Nomor 11");
        V11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V11.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                V11MouseEntered(evt);
            }
        });

        V12.setBackground(new java.awt.Color(0, 0, 0));
        V12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        V12.setForeground(new java.awt.Color(255, 255, 255));
        V12.setText("Nomor 12");
        V12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        V12.setMargin(new java.awt.Insets(2, 3, 2, 3));
        V12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                V12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(V1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(V2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(V3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(V4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(V5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(V6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(V7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(V11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(V10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpinnerV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MarkV)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(V1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(V6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V7))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(V11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(V12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(V10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(SpinnerV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarkV)))
        );

        jPanel13.setOpaque(false);

        H1.setBackground(new java.awt.Color(0, 0, 0));
        H1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H1.setForeground(new java.awt.Color(255, 255, 255));
        H1.setText("Nomor 1");
        H1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H1.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H1MouseClicked(evt);
            }
        });

        H2.setBackground(new java.awt.Color(0, 0, 0));
        H2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H2.setForeground(new java.awt.Color(255, 255, 255));
        H2.setText("Nomor 2");
        H2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H2.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H2MouseClicked(evt);
            }
        });

        H3.setBackground(new java.awt.Color(0, 0, 0));
        H3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H3.setForeground(new java.awt.Color(255, 255, 255));
        H3.setText("Nomor 3");
        H3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H3.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H3MouseClicked(evt);
            }
        });

        H4.setBackground(new java.awt.Color(0, 0, 0));
        H4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H4.setForeground(new java.awt.Color(255, 255, 255));
        H4.setText("Nomor 4");
        H4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H4.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H4MouseClicked(evt);
            }
        });

        H5.setBackground(new java.awt.Color(0, 0, 0));
        H5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H5.setForeground(new java.awt.Color(255, 255, 255));
        H5.setText("Nomor 5");
        H5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H5.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H5MouseClicked(evt);
            }
        });

        H6.setBackground(new java.awt.Color(0, 0, 0));
        H6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H6.setForeground(new java.awt.Color(255, 255, 255));
        H6.setText("Nomor 6");
        H6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H6.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                H6MouseDragged(evt);
            }
        });
        H6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H6MouseClicked(evt);
            }
        });

        H7.setBackground(new java.awt.Color(0, 0, 0));
        H7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H7.setForeground(new java.awt.Color(255, 255, 255));
        H7.setText("Nomor 7");
        H7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H7.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H7MouseClicked(evt);
            }
        });

        H8.setBackground(new java.awt.Color(0, 0, 0));
        H8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H8.setForeground(new java.awt.Color(255, 255, 255));
        H8.setText("Nomor 8");
        H8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H8.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H8MouseClicked(evt);
            }
        });

        H9.setBackground(new java.awt.Color(0, 0, 0));
        H9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H9.setForeground(new java.awt.Color(255, 255, 255));
        H9.setText("Nomor 9");
        H9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H9.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H9MouseClicked(evt);
            }
        });

        H10.setBackground(new java.awt.Color(0, 0, 0));
        H10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H10.setForeground(new java.awt.Color(255, 255, 255));
        H10.setText("Nomor 10");
        H10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H10.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H10MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("MENDATAR");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Nomor");

        SpinnerH.setModel(new javax.swing.SpinnerNumberModel(1, 1, 13, 1));

        MarkH.setBackground(new java.awt.Color(0, 0, 0));
        MarkH.setForeground(new java.awt.Color(255, 255, 255));
        MarkH.setText("Mark");
        MarkH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarkHMouseClicked(evt);
            }
        });

        H11.setBackground(new java.awt.Color(0, 0, 0));
        H11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H11.setForeground(new java.awt.Color(255, 255, 255));
        H11.setText("Nomor 11");
        H11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H11.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H11MouseClicked(evt);
            }
        });

        H12.setBackground(new java.awt.Color(0, 0, 0));
        H12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H12.setForeground(new java.awt.Color(255, 255, 255));
        H12.setText("Nomor 12");
        H12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H12.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H12MouseClicked(evt);
            }
        });

        H13.setBackground(new java.awt.Color(0, 0, 0));
        H13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        H13.setForeground(new java.awt.Color(255, 255, 255));
        H13.setText("Nomor 13");
        H13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        H13.setMargin(new java.awt.Insets(2, 3, 2, 3));
        H13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(H6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(H7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(H8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(H9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(H11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(H12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(H13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(H10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel16))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpinnerH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MarkH)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(H1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(H6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H8))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(H11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(H13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(H10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(SpinnerH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarkH)))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("JAWABAN TTS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(Kembali)
                                .addGap(79, 79, 79))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(1, 1, 1)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Kembali)
                .addGap(16, 16, 16))
        );

        LabelTimer.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTimer.setText("00:00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(PanelTTS, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelTTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SCORE TABLE");

        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(1024, 85));

        jPanel9.setOpaque(false);

        Score3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score3.setText("0");

        AddButton3.setBackground(new java.awt.Color(0, 0, 0));
        AddButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton3.setForeground(new java.awt.Color(255, 255, 255));
        AddButton3.setText("add");
        AddButton3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton3MouseClicked(evt);
            }
        });

        TambahanScore3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore3.setText("0");
        TambahanScore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore3ActionPerformed(evt);
            }
        });

        NamaTim3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim3.setText(" ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(TambahanScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddButton3)))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(NamaTim3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton3)
                    .addComponent(TambahanScore3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel10.setOpaque(false);

        Score5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score5.setText("0");

        AddButton5.setBackground(new java.awt.Color(0, 0, 0));
        AddButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton5.setForeground(new java.awt.Color(255, 255, 255));
        AddButton5.setText("add");
        AddButton5.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AddButton5MouseDragged(evt);
            }
        });
        AddButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton5MouseClicked(evt);
            }
        });

        TambahanScore5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore5.setText("0");
        TambahanScore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore5ActionPerformed(evt);
            }
        });

        NamaTim5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim5.setText(" ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(TambahanScore5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddButton5)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(NamaTim5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton5)
                    .addComponent(TambahanScore5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel11.setOpaque(false);

        Score2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score2.setText("0");

        TambahanScore2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore2.setText("0");
        TambahanScore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore2ActionPerformed(evt);
            }
        });

        AddButton2.setBackground(new java.awt.Color(0, 0, 0));
        AddButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton2.setForeground(new java.awt.Color(255, 255, 255));
        AddButton2.setText("add");
        AddButton2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton2MouseClicked(evt);
            }
        });

        NamaTim2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim2.setText(" ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TambahanScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(AddButton2)))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(NamaTim2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton2)
                    .addComponent(TambahanScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel12.setOpaque(false);

        Score4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score4.setText("0");

        AddButton4.setBackground(new java.awt.Color(0, 0, 0));
        AddButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton4.setForeground(new java.awt.Color(255, 255, 255));
        AddButton4.setText("add");
        AddButton4.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton4MouseClicked(evt);
            }
        });

        TambahanScore4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore4.setText("0");
        TambahanScore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore4ActionPerformed(evt);
            }
        });

        NamaTim4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim4.setText(" ");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaTim4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(TambahanScore4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(AddButton4)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(Score4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(NamaTim4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton4)
                    .addComponent(TambahanScore4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(Score4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jPanel8.setOpaque(false);

        NamaTim1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaTim1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NamaTim1.setText(" ");

        Score1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Score1.setText("0");

        AddButton1.setBackground(new java.awt.Color(0, 0, 0));
        AddButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddButton1.setForeground(new java.awt.Color(255, 255, 255));
        AddButton1.setText("add");
        AddButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        AddButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButton1MouseClicked(evt);
            }
        });

        TambahanScore1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TambahanScore1.setText("0");
        TambahanScore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahanScore1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(AddButton1)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(Score1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamaTim1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(TambahanScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(NamaTim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Score1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddButton1)
                    .addComponent(TambahanScore1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(585, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KembaliMouseClicked
       try {
            GrandFinal.UpdateDataFile("DataTeam.txt");
        } catch (IOException ex) {
            Logger.getLogger(TTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        if ( countdownTimer.isRunning())
            countdownTimer.stop();
        MainFrame.SetNewPanel("GrandFinal");
    }//GEN-LAST:event_KembaliMouseClicked

    private void H1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H1MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==1)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H1MouseClicked

    private void H2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H2MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==2)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H2MouseClicked

    private void H3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H3MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==3)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H3MouseClicked

    private void V1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V1MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==1)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V1MouseClicked

    private void V2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V2MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==2)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V2MouseClicked

    private void V3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V3MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==3)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V3MouseClicked

    private void V4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V4MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==4)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V4MouseClicked

    private void MarkHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarkHMouseClicked
        int NoSoal = (int)SpinnerH.getValue();
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==NoSoal){
                int X = ListSoal.elementAt(i).StartIdxX;
                int Y = ListSoal.elementAt(i).StartIdxY;
                //ke kanan
                int ii = Y;
                while (!Kolom[X][ii].IsNoSoalSama(0)){
                    UpdateGambarTepi(X,ii);
                    ii++;
                }
            }
        }
    }//GEN-LAST:event_MarkHMouseClicked

    private void MarkVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarkVMouseClicked
        int NoSoal = (int)SpinnerV.getValue();
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==NoSoal){
                int X = ListSoal.elementAt(i).StartIdxX;
                int Y = ListSoal.elementAt(i).StartIdxY;
                //ke bawah
                int ii = X;
                while (!Kolom[ii][Y].IsNoSoalSama(0)){
                    UpdateGambarTepi(ii,Y);
                    ii++;
                }
            }
        }
    }//GEN-LAST:event_MarkVMouseClicked

    private void H4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H4MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==4)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H4MouseClicked

    private void H5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H5MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==5)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H5MouseClicked

    private void H6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_H6MouseDragged

    private void H6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H6MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==6)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H6MouseClicked

    private void H7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H7MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==7)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H7MouseClicked

    private void H8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H8MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==8)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H8MouseClicked

    private void H9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H9MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==9)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H9MouseClicked

    private void H10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H10MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==10)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H10MouseClicked

    private void H11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H11MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==11)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H11MouseClicked

    private void H12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H12MouseClicked
       for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==12)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H12MouseClicked

    private void H13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H13MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(!ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==13)
            ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_H13MouseClicked

    private void V5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V5MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==5)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V5MouseClicked

    private void V6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_V6MouseDragged

    private void V6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V6MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==6)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V6MouseClicked

    private void V7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V7MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==7)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V7MouseClicked

    private void V8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V8MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==8)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V8MouseClicked

    private void V9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V9MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==9)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V9MouseClicked

    private void V10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V10MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==10)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V10MouseClicked

    private void V11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_V11MouseEntered

    private void V11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V11MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==11)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V11MouseClicked

    private void V12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_V12MouseClicked
        for(int i = 0; i < ListSoal.size() ; i ++){
            if(ListSoal.elementAt(i).IsVertikal && ListSoal.elementAt(i).NoSoal==12)
                ListSoal.elementAt(i).CetakJawaban();
        }
    }//GEN-LAST:event_V12MouseClicked

    private void AddButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton3MouseClicked
        String str = TambahanScore3.getText();
        GrandFinal.Tim.elementAt(2).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore3.setText("0");
    }//GEN-LAST:event_AddButton3MouseClicked

    private void TambahanScore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore3ActionPerformed

    private void AddButton5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButton5MouseDragged

    private void AddButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton5MouseClicked
        String str = TambahanScore5.getText();
        GrandFinal.Tim.elementAt(4).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore5.setText("0");
    }//GEN-LAST:event_AddButton5MouseClicked

    private void TambahanScore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore5ActionPerformed

    private void TambahanScore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore2ActionPerformed

    private void AddButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton2MouseClicked
        String str = TambahanScore2.getText();
        GrandFinal.Tim.elementAt(1).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore2.setText("0");
    }//GEN-LAST:event_AddButton2MouseClicked

    private void AddButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton4MouseClicked
        String str = TambahanScore4.getText();
        GrandFinal.Tim.elementAt(3).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore4.setText("0");
    }//GEN-LAST:event_AddButton4MouseClicked

    private void TambahanScore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore4ActionPerformed

    private void AddButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButton1MouseClicked
        String str = TambahanScore1.getText();
        GrandFinal.Tim.elementAt(0).AddScore(Integer.parseInt(str));
        UpdateScoreTable();
        TambahanScore1.setText("0");
    }//GEN-LAST:event_AddButton1MouseClicked

    private void TambahanScore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahanScore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TambahanScore1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        NamaTim1.setText(GrandFinal.Tim.elementAt(0).Nama);
        NamaTim2.setText(GrandFinal.Tim.elementAt(1).Nama);
        NamaTim3.setText(GrandFinal.Tim.elementAt(2).Nama);
        NamaTim4.setText(GrandFinal.Tim.elementAt(3).Nama);
        NamaTim5.setText(GrandFinal.Tim.elementAt(4).Nama);
        
        countdownTimer = new Timer(1000, new TTS.CountdownTimerListener(DefaultTime));
        countdownTimer.start();
        UpdateScoreTable();
    }//GEN-LAST:event_formComponentShown
    
    public void LoadTTSFromFile (String fileName) throws IOException{
    	BufferedReader reader = new BufferedReader(new FileReader(fileName));
    	String line = null;
    	while ((line = reader.readLine()) != null) {
            String parts[] = line.split(" ");
            SoalTTS Soal = new SoalTTS(Integer.parseInt(parts[1]),
                    Integer.parseInt(parts[2]),
                    parts[0].charAt(0),Integer.parseInt(parts[3]),
                    reader.readLine().trim());
            ListSoal.add(Soal);
    	}
        reader.close();
    }
    
    class CountdownTimerListener implements ActionListener{
        int timeRemaining ;
        
        public CountdownTimerListener(int Time){
            timeRemaining = Time;
        }
    
        @Override
        public void actionPerformed(ActionEvent e) {
            if (--timeRemaining > 0){
                repaintLabel(timeRemaining);
            }else{
                LabelTimer.setText("Time's up!");
                countdownTimer.stop();
            }
        }
    }
    
    public void UpdateScoreTable(){
        Score1.setText(String.valueOf(GrandFinal.Tim.elementAt(0).Score));
        Score2.setText(String.valueOf(GrandFinal.Tim.elementAt(1).Score));
        Score3.setText(String.valueOf(GrandFinal.Tim.elementAt(2).Score));
        Score4.setText(String.valueOf(GrandFinal.Tim.elementAt(3).Score));
        Score5.setText(String.valueOf(GrandFinal.Tim.elementAt(4).Score));
    }
    
    public void repaintLabel(int Second){
        int hh = Second/3600;
        int mm = (Second%3600)/60;
        int ss = (Second%3600)%60;
        String StrHH, StrMM, StrSS;
        if (hh < 10)
            StrHH = new String("0"+hh);
        else
            StrHH = new String(Integer.toString(hh));
        if (mm < 10)
            StrMM = new String("0"+mm);
        else
            StrMM = new String(Integer.toString(mm));
        if (ss < 10)
            StrSS = new String("0"+ss);
        else
            StrSS = new String(Integer.toString(ss));
        String Jam = new String(StrHH+":"+StrMM+":"+StrSS);
        
        LabelTimer.setText(Jam);
    }
    
    public void AddComponent(){
        boolean shouldFill = true;
        PanelTTS.setLayout(new GridBagLayout());
        PanelTTS.setVisible(true);
        GridBagConstraints c = new GridBagConstraints();
	if (shouldFill) {
	//natural height, maximum width
	c.fill = GridBagConstraints.CENTER;
	}
        ///*
        for (int i = 0 ; i < TinggiKolom ;  i++){
            for (int j = 0 ; j < LebarKolom ; j ++){               
                if(!Kolom[i][j].terjawab){
                    
                    if(Kolom[i][j].Huruf=='@')
                        Kolom[i][j].LengkapiImagePanel("img/test/NoBorder16.png",i,j);
                    else
                        Kolom[i][j].LengkapiImagePanel("img/test/Border16.png",i,j);
                    Kolom[i][j].setPreferredSize(new Dimension(Kolom[i][j].image.getWidth(),Kolom[i][j].image.getHeight()));
                }
                c.gridy = i;
                c.gridx = j;
                PanelTTS.add(Kolom[i][j],c);
            }
        }
    }
    
    public static void ChangeBorder(int X, int Y){
        int NoSoal = Kolom[X][Y].NoSoal();
        //System.out.println("Soal "+NoSoal);
        if(((!Kolom[X][Y+1].IsNoSoalSama(0) || !Kolom[X][Y-1].IsNoSoalSama(0))&&
                (!Kolom[X-1][Y].IsNoSoalSama(0) && !Kolom[X+1][Y].IsNoSoalSama(0)))
                ||
                ((!Kolom[X+1][Y].IsNoSoalSama(0) || !Kolom[X-1][Y].IsNoSoalSama(0))&&
                (!Kolom[X][Y-1].IsNoSoalSama(0) && !Kolom[X][Y+1].IsNoSoalSama(0)))
                ){
            System.out.println("dua banget  "+NoSoal);
            int i = X;
            //ke bawah
            while (!Kolom[i][Y].IsNoSoalSama(0)){
                UpdateGambarTepi(i,Y);
                i++;
            }
            i = X;
            //ke atas
            while (!Kolom[i][Y].IsNoSoalSama(0)){
                UpdateGambarTepi(i,Y);
                i--;
            }
             
            //ke kanan
            i = Y;
            while (!Kolom[X][i].IsNoSoalSama(0)){
                UpdateGambarTepi(X,i);
                i++;
            }
            
            //ke kiri
            i = Y;
            while (!Kolom[X][i].IsNoSoalSama(0)){
                UpdateGambarTepi(X,i);
                i--;
            }
        }else
        if (Kolom[X][Y+1].IsNoSoalSama(0) && Kolom[X][Y-1].IsNoSoalSama(0)){
            System.out.println("Satu Vertikal");
            int i = X+1;
            //ke bawah
            while (!Kolom[i][Y].IsNoSoalSama(0)){
                UpdateGambarTepi(i,Y);
                i++;
            }
            i = X;
            //ke atas
            while (!Kolom[i][Y].IsNoSoalSama(0)){
                UpdateGambarTepi(i,Y);
                i--;
            }
            
        }else if(Kolom[X+1][Y].IsNoSoalSama(0) && Kolom[X-1][Y].IsNoSoalSama(0)){
            System.out.println("Satu Horizontal");
            //ke kanan
            int i = Y+1;
            while (!Kolom[X][i].IsNoSoalSama(0)){
                UpdateGambarTepi(X,i);
                i++;
            }
            
            //ke kiri
            i = Y;
            while (!Kolom[X][i].IsNoSoalSama(0)){
                UpdateGambarTepi(X,i);
                i--;
            }
            
        }else{
            System.out.println("Dua");
            int i = X;
            //ke bawah
            while (!Kolom[i][Y].IsNoSoalSama(0)){
                UpdateGambarTepi(i,Y);
                i++;
            }
            i = X;
            //ke atas
            while (!Kolom[i][Y].IsNoSoalSama(0)){
                UpdateGambarTepi(i,Y);
                i--;
            }
             
            //ke kanan
            i = Y;
            while (!Kolom[X][i].IsNoSoalSama(0)){
                UpdateGambarTepi(X,i);
                i++;
            }
            
            //ke kiri
            i = Y;
            while (!Kolom[X][i].IsNoSoalSama(0)){
                UpdateGambarTepi(X,i);
                i--;
            }
        }
                
    }
    
    public static void UpdateGambarTepi(int X, int Y){
        if (!Kolom[X][Y].IsNoSoalSama(0)&&!Kolom[X][Y].terjawab){
            try {
                if (Kolom[X][Y].IsTepiMerah){
                    Kolom[X][Y].IsTepiMerah = false;
                    Kolom[X][Y].image = ImageIO.read(new File("img/test/Border16.png"));
                }else{
                    Kolom[X][Y].image = ImageIO.read(new File("img/test/RedBorder16.png"));
                    Kolom[X][Y].IsTepiMerah = true;                    
                }
                 Kolom[X][Y].setPreferredSize(new Dimension(Kolom[X][Y].image.getWidth(),Kolom[X][Y].image.getHeight()));
                Kolom[X][Y].repaint();
            } catch (IOException ex) {
                Logger.getLogger(TTS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void BeriPembatasHitam(){
        for(int X = 0; X < TinggiKolom; X++){
            for(int Y = 0 ; Y < LebarKolom ; Y++){
                if ((X==0)||(Y==0)||(X==TinggiKolom-1)||(Y==LebarKolom-1)){
                    try {
                        Kolom[X][Y].image = ImageIO.read(new File("img/test/Black.png"));
                        Kolom[X][Y].setPreferredSize(new Dimension(Kolom[X][Y].image.getWidth(),Kolom[X][Y].image.getHeight()));
                        Kolom[X][Y].repaint();
                    } catch (IOException ex) {
                        Logger.getLogger(TTS.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
            
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton1;
    private javax.swing.JButton AddButton2;
    private javax.swing.JButton AddButton3;
    private javax.swing.JButton AddButton4;
    private javax.swing.JButton AddButton5;
    private javax.swing.JButton H1;
    private javax.swing.JButton H10;
    private javax.swing.JButton H11;
    private javax.swing.JButton H12;
    private javax.swing.JButton H13;
    private javax.swing.JButton H2;
    private javax.swing.JButton H3;
    private javax.swing.JButton H4;
    private javax.swing.JButton H5;
    private javax.swing.JButton H6;
    private javax.swing.JButton H7;
    private javax.swing.JButton H8;
    private javax.swing.JButton H9;
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel LabelTimer;
    private javax.swing.JButton MarkH;
    private javax.swing.JButton MarkV;
    private javax.swing.JLabel NamaTim1;
    private javax.swing.JLabel NamaTim2;
    private javax.swing.JLabel NamaTim3;
    private javax.swing.JLabel NamaTim4;
    private javax.swing.JLabel NamaTim5;
    private javax.swing.JPanel PanelTTS;
    private javax.swing.JLabel Score1;
    private javax.swing.JLabel Score2;
    private javax.swing.JLabel Score3;
    private javax.swing.JLabel Score4;
    private javax.swing.JLabel Score5;
    private javax.swing.JSpinner SpinnerH;
    private javax.swing.JSpinner SpinnerV;
    private javax.swing.JTextField TambahanScore1;
    private javax.swing.JTextField TambahanScore2;
    private javax.swing.JTextField TambahanScore3;
    private javax.swing.JTextField TambahanScore4;
    private javax.swing.JTextField TambahanScore5;
    private javax.swing.JButton V1;
    private javax.swing.JButton V10;
    private javax.swing.JButton V11;
    private javax.swing.JButton V12;
    private javax.swing.JButton V2;
    private javax.swing.JButton V3;
    private javax.swing.JButton V4;
    private javax.swing.JButton V5;
    private javax.swing.JButton V6;
    private javax.swing.JButton V7;
    private javax.swing.JButton V8;
    private javax.swing.JButton V9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
